INSERT INTO SP_BUILDING(ID, NAME) VALUES(0, '158 Cours Fauriel');
INSERT INTO SP_BUILDING(ID, NAME) VALUES(1, 'Espace Fauriel');

INSERT INTO SP_ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-10, 'Room1', 1, 0 );
INSERT INTO SP_ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-9, 'Room2', 1, 1);

INSERT INTO SP_LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-1, 8, 'ON', -10);
INSERT INTO SP_LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-2, 0, 'OFF', -10);