INSERT INTO BUILDING(ID, NAME) VALUES(0, '158 Cours Fauriel');
INSERT INTO BUILDING(ID, NAME) VALUES(1, 'Espace Fauriel');

INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(0, 'Room0', 1, 0 );
INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(1, 'Room1', 1, 1);

INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (0, 8, 'ON', 0);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (1, 0, 'OFF', 1);